### ISSUE TITLE
Dynamic Room Environment

### ISSUE THREAD

**Issue by bhairavmehta95** [maximecb/gym-minigrid#1]
Is there an easy way to change the grid between different episodes?

I am looking to recreate some of the dynamic room environments, i.e where a shortcut opens up or a goal changes location after a certain number of timesteps or episodes.

**Comment by maximecb** [comment]
Hi @bhairavmehta95. I made a commit just yesterday which makes this the default behavior: https://github.com/maximecb/gym-minigrid/commit/127eef302c4e52f0b976c10304a2b33390fbca78

Each time an episode ends, when you call the `env.reset()` method, this internally calls `_genGrid()`. The `_genGrid()` method should produce a new random grid for your environment.

For example, the Door-Key environment, the splitting wall and the position of the door change randomly: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/envs/simple_envs.py#L34

**Comment by bhairavmehta95** [comment]
Great! Exactly what I was looking for
