### ISSUE TITLE
Agent can see around walls

### ISSUE THREAD

**Issue by PSmith4** [maximecb/gym-minigrid#101]
Hello, 
   the current Grid.process_vis is allowing the agent to see around walls if the wall is horizontal, relative to the agent. 
This is due to the horizontal processing of the visible area cascading around the walled cells.

I have included an example of this light-curving vision and the tree node that shows how each cell mask is being activated (the first time)
![image](https://user-images.githubusercontent.com/17971992/86331413-68ec9580-bc8c-11ea-99be-f6192a57bb63.png)
![image](https://user-images.githubusercontent.com/17971992/86331752-db5d7580-bc8c-11ea-9f70-98652d5561e6.png)

I believe a potential fix of this is to use a sequence of beam emulations. it may be less computationally effective but does produce more accurate vision.  Code attached

  def border(grid, agent_pos):
        if hasattr(grid,"sett"): return grid.sett
        grid.sett=[]
        for j in range(0,grid.height):
            grid.sett.append([0-agent_pos[0], j])
            grid.sett.append([grid.width-1-agent_pos[0], j])
        for i in range(1-agent_pos[0], grid.width-1-agent_pos[0]):
            grid.sett.append([i, grid.height-1])
        #print(sett)
        return grid.sett
  def process_vis(grid, agent_pos):
        mask = np.zeros(shape=(grid.width, grid.height), dtype=np.bool)
        mask[agent_pos[0], agent_pos[1]] = True
        for b in grid.border(agent_pos):
            angle=math.atan2(b[1],b[0])
            #print(angle)
            beam_range=1
            while(True):
                x,y = round(agent_pos[0]+beam_range*math.cos(angle)), round(agent_pos[1]-beam_range*math.sin(angle))    
                #print("-",x,y)
                if(x<0 or x>= grid.width or y<0 or y>= grid.height):
                    break
                mask[x,y]=True
                cell = grid.get(x, y)
                if cell and not cell.see_behind():
                    break
                beam_range+=1
        for j in range(0, grid.height):
            for i in range(0, grid.width):
                if not mask[i, j]:
                    grid.set(i, j, None)
        return mask

**Comment by maximecb** [comment]
Hi Phillip. I know it doesn't look realistic, but it's hard to realistically emulate the way 3D vision works in 2D. As it is, the agent can't see through closed doors, which I feel is generally good enough.
