### ISSUE TITLE
Goal tile vanishes when agent reaches goal

### ISSUE THREAD

**Issue by etaoxing** [maximecb/gym-minigrid#102]
When using RGBImgObsWrapper, the green goal tile disappears from the partial observation once the agent reaches the goal tile.

![start](https://user-images.githubusercontent.com/9792332/86497069-18d60780-bd4e-11ea-9987-c2b12a335ffc.png)
![goal_reached_no_green_tile](https://user-images.githubusercontent.com/9792332/86496901-4bcbcb80-bd4d-11ea-9d9d-734956f7aa66.png)

To reproduce:
```
# manual_control.py, line 33
if done:
    print('done!')
    from PIL import Image
    Image.fromarray(obs).show()
```

`./manual_control.py --env MiniGrid-Empty-6x6-v0 --agent_view`

**Comment by maximecb** [comment]
Want to try to debug it? :)

**Comment by etaoxing** [comment]
Sure thing! Submitted a pull request that should fix the goal rendering. Might have found another issue with the rendering of doors though, #104 .

**Comment by maximecb** [comment]
After looking at this more, I don't think this fix is needed. The observation you get after done is *after* the episode has ended. At that point, the agent is not able to take any further actions.

**Comment by etaoxing** [comment]
Ok, thanks for taking a look! Wasn't sure if this was intended behavior for the goal, because of the optional 'done' action.
