### ISSUE TITLE
Opened doors render differently depending on agent_dir

### ISSUE THREAD

**Issue by etaoxing** [maximecb/gym-minigrid#104]
Opened doors change position depending on the direction the agent is facing.

![combined](https://user-images.githubusercontent.com/9792332/86518250-31055f80-bdfe-11ea-9538-5eef12a01e44.jpg)
[open_doors.zip](https://github.com/maximecb/gym-minigrid/files/4873491/open_doors.zip)

**Comment by maximecb** [comment]
Seems acceptable to me.

**Comment by etaoxing** [comment]
Sorry, the observations were stitched together in the wrong order so it may have been unclear, updated it above. Could you take another look at this?

In particular:
![10](https://user-images.githubusercontent.com/9792332/86606088-8d3ebf80-bf75-11ea-93bf-33c7cdbe44dd.png) ![17](https://user-images.githubusercontent.com/9792332/86606037-78fac280-bf75-11ea-8dce-483447281c4b.png) ![18](https://user-images.githubusercontent.com/9792332/86606046-7c8e4980-bf75-11ea-968f-1d9a5028a5da.png)

**Comment by maximecb** [comment]
It's because doors are not directional objects. They occupy one grid cell, but they don't have an orientation per-se.
