### ISSUE TITLE
Matplotlib warning (possible future error) 

### ISSUE THREAD

**Issue by fatemi** [maximecb/gym-minigrid#109]
window.py#L29-L30

`ax.set_xticks([], [])` and `ax.set_yticks([], [])`  have been deprecated since Matplotlib 3.2. For now, it is only a warning message, but in the future it may become a full error. 

Perhaps you can replace them with the following:
```
ax.xaxis.set_ticks_position('none')
ax.yaxis.set_ticks_position('none')
_ = ax.set_xticklabels([])
_ = ax.set_yticklabels([])
```

**Comment by maximecb** [comment]
Would you be kind enough to test the change and submit a PR?
