### ISSUE TITLE
Does arrow keys work in manual control?

### ISSUE THREAD

**Issue by raymondchua** [maximecb/gym-minigrid#115]
Hi, 
I am having difficulty navigating my agent around the environment when I run the manual_control file. Specifically, the arrow keys does not seem to have any effect. Does anyone face the same problem?

**Comment by maximecb** [comment]
It seems to work fine on my Linux machine with the latest matplotlib and Python 3.6.9

What platform are you on?

**Comment by raymondchua** [comment]
It works now after I upgrade to the latest Matplotlib and Python.
