### ISSUE TITLE
Dynamic obstacles environment

### ISSUE THREAD

**Issue by Eksanf** [maximecb/gym-minigrid#117]
I wonder is there any RL implementation for the Dynamic obstacles environment.

**Comment by maximecb** [comment]
Hi @Eksanf. I'm not sure what you mean? All of the MiniGrid environments can be used for RL, including the dynamic obstacles environment?

**Comment by Eksanf** [comment]
Thanks， @maximecb . I want to find the specific RL  implementation methods or papers  for the Dynamic obstacles environment.
