### ISSUE TITLE
agent_view_size for RoomGrid

### ISSUE THREAD

**Issue by aadeshnpn** [maximecb/gym-minigrid#118]
Currently, the environments that inherits RoomGrid class doesn't have the ability to set agent_view_size. By default all the agents in those environment are initialized with 7 as agent_view_size. It is useful in many cases to have this flexibility for environments with RoomGrid class as parent. 

![image](https://user-images.githubusercontent.com/1760420/99109109-4f524780-25b6-11eb-88e6-5de14f4c6667.png)

I have already fixed this issue if the team wants to merge this feature to the master branch. 

Thanks,
Aadesh

**Comment by maximecb** [comment]
Hi @aadeshnpn. Sure that would be a useful fix. Feel free to open a pull request.
