### ISSUE TITLE
If a box does not contain anything, should opening it make it disappear?

### ISSUE THREAD

**Issue by smspillaz** [maximecb/gym-minigrid#121]
I'm looking into a peculiar behavior with one of my agents in a goal-conditioned setting, where the agent learns to open boxes in the room because doing so reduces the complexity of the problem (reduces the number of distractor objects / clears the way).

The main line of interest is here: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L324 . If `contains` is `None` then the grid cell gets replaced with nothing.

My immediate thought is that opening an empty box should just do nothing, but maybe I'm wrong. Is this behavior intentional?

**Comment by maximecb** [comment]
I like that the behavior is simple and uniform to be honest. Otherwise, it seems fairly arbitrary. It's easy to change it in your fork if you want to, but I'd rather not change it here because it might affect the behavior of a lot of published code.

**Comment by smspillaz** [comment]
Fair enough. I was thinking that breaking existing code was probably the main trade-off.
