### ISSUE TITLE
Memory environments solved already?

### ISSUE THREAD

**Issue by MarcoMeter** [maximecb/gym-minigrid#122]
Hi @maximecb 
do you know of any recurrent policy implementation that reliably solves your memory environments?

I'm currently working on my own recurrent PPO policy implementation.
It works well for CartPole (masked velocity) and Unity Hallway, but for MiniGrid using visual observations (84x84x3), it usually collapses entirely.

My guess is that initializing hidden states to zero causes this behavior.
I did grid search for many hyperparameters and tried a fully connected layer between the visual encoder and the LSTM to reduce the LSTM's inputs. Like CartPole has only 4 and Hallway 108. My visual encoder produces 3136 outputs that are fed to the LSTM.

I also implemented a fake recurrence, which stores hidden states along the experience tuples for each step. That works pretty well, but completely discards the usage of bptt as no sequences are fed anymore.

**Comment by maximecb** [comment]
Hi @MarcoMeter 

The RL implementation in the babyai repo is able to solve this. You should use the `train_rl.py` script to train it:
https://github.com/mila-iqia/babyai/blob/master/scripts/README.md

Trying to solve this environment has actually exposed multiple bugs in our implementation of memory. It's tricky to get right.
