### ISSUE TITLE
Four-rooms environment

### ISSUE THREAD

**Issue by maximecb** [maximecb/gym-minigrid#13]
I think it might be useful to implement the classic "four rooms" environment, which is used in many classic reinforcement learning papers.

Eg: http://rstb.royalsocietypublishing.org/content/royptb/369/1655/20130480/F2.large.jpg?width=800&height=600&carousel=1

The environment should ideally have configurable start and goal positions, as parameters to the constructor. If these are not specified, they should be chosen at random every time the environment is reset.

**Comment by d3sm0** [comment]
@maximecb How would you like to see this implemented? As a seperat class that inherits from MiniGrdiEnv? or as an instance of MultiRoomEnv?

OT: Can i do some renaming following pep8 convention?

**Comment by maximecb** [comment]
I think either is fine, but there are no doors in the classical four-room env.

Wrt renaming, it depends if it's a field people are likely to directly access or not. Have to keep in mind there are a number of people using this code, and we'd rather not break it if possible.

**Comment by d3sm0** [comment]
sorry i just saw that you had a Playground-v0 implemented that works great. 
Ok for the renaming. thx.
