### ISSUE TITLE
RedBlueDoors solved without memory

### ISSUE THREAD

**Issue by SamNPowers** [maximecb/gym-minigrid#134]
MiniGrid-RedBlueDoors-6x6-v0 can be solved by PPO (tested using rl_starter_files) using the default settings and no memory whatsoever. My guess is it's because the environment is too small, so the agent never encounters an observation that has two optimal actions depending on previous context.

Thus far I have not observed the larger 8x8 having this issue.

**Comment by maximecb** [comment]
Yes you are correct, and it's sometimes surprising which environments can be solved without memory.

Maybe we should mention in the README that MiniGrid-RedBlueDoors-6x6-v0 is solvable without memory.

**Comment by SamNPowers** [comment]
Ah, 8x8 was also solvable without memory, just took longer. 

Anyhow, yeah, it'd be convenient if they were clearly marked in the README as whether memory was actually required to solve them. I was surprised by this finding.

**Comment by maximecb** [comment]
I updated the README.

I believe that `MiniGrid-MemoryS13-v0` for sure is not solvable without memory, and possibly `MiniGrid-MemoryS11-v0` as well. Please let me know if you manage to solve `MiniGrid-MemoryS11-v0` without memory, and if that's the case, I will remove it from the readme.
