### ISSUE TITLE
What does the '9' in MiniGrid-LavaCrossingS9N1 mean?

### ISSUE THREAD

**Issue by drozzy** [maximecb/gym-minigrid#138]
So I understand that 1,2,3,5 in N1,2,3,5 is the number of lava channels.

But what does the numbers in S9 and S11 represent? Just curious.

MiniGrid-LavaCrossingS9N1-v0
MiniGrid-LavaCrossingS9N2-v0
MiniGrid-LavaCrossingS9N3-v0
MiniGrid-LavaCrossingS11N5-v0

**Comment by maximecb** [comment]
It's the size of the environment, width of the grid.
