### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by potato23333** [maximecb/gym-minigrid#139]
While using the env.render(), it did not work. Image drawn by pyplot  was blank.
  Is there any function can create a window to display

**Comment by maximecb** [comment]
This should create a window. Can you provide some details about your OS, platform, etc?

Also, do you see a window when you run `./manual_control.py` ?

**Comment by potato23333** [comment]
I use pycharm on windows
I can see a window when run manual_control in cmd

**Comment by BBDrive** [comment]
Uncheck pycharm->Settings->Tools->Python Scientific->Show plots in tool window

**Comment by maximecb** [comment]
What he suggested, and I would say that if it works in `manual_control.py`, there has to be a way to make it work in your script. Start from `manual_control.py` as a base.
