### ISSUE TITLE
bug in gen_obs_grid?

### ISSUE THREAD

**Issue by pierg** [maximecb/gym-minigrid#14]
Hello,

It seems to me that the sub-grid observed by the agent is somtimes wrong depending on what is the agent direction.
For example, assuming that we have a AGENT_VIEW_SIZE or 3. We will have a grid 3x3 around the agent and 9 elements in the observation array.  
Here are the indexes of the elements in the grid visible by the agent that is facing up and is positioned in the center-bottom of the grid.

8      7      6
5      4      3
2      **A**      0

In this example shouldn't the index **8** of the observation array always be the element that the agent percieves at its **top-left** corner and the element of idex **0** always be the one at **bottom-right** (and so on..)?

It seems that in the current implementation of gen_obs_grid the positions of the elements in the observation view of the agent are not consistent with their position in the actual sub-grid generated as observation _when it rotates_.

`

        topX, topY, botX, botY = self.get_view_exts()

        grid = self.grid.slice(topX, topY, AGENT_VIEW_SIZE, AGENT_VIEW_SIZE)

        for i in range(self.agent_dir + 1):
            grid = grid.rotate_left()
`

I tried with a very naive and not optimized implementation to fix this issue:

`

        topX, topY, botX, botY = self.get_view_exts()

        grid = self.grid.slice(topX, topY, AGENT_VIEW_SIZE, AGENT_VIEW_SIZE)
        grid_rotate_left_1 = grid
        grid_rotate_left_2 = grid
        grid_rotate_left_3 = grid

        grid_rotate_left_1 = grid_rotate_left_1.rotate_left()

        for i in range (2):
            grid_rotate_left_2 = grid_rotate_left_2.rotate_left()

        for i in range (3):
            grid_rotate_left_3 = grid_rotate_left_3.rotate_left()

        # agent facing right
        if self.agent_dir == 0:
            grid = grid_rotate_left_3
        # agent facing left
        elif self.agent_dir == 2:
            grid = grid_rotate_left_1
        # agent facing up
        elif self.agent_dir == 3:
            grid = grid_rotate_left_2

`

What do you think about this?

Thank you for your collaboration!
Pier

**Comment by maximecb** [comment]
I'm not sure I fully understand what the issue is here. It's normal that the agent view is rotated. It's made so that the agent sees what is in front of it from an egocentric reference frame. Can you describe the problem in more details? Does it happen with the default 7x7 observation size?

**Comment by pierg** [comment]
Yes the view has to rotate, but it didn't. 
It's my bad actually, I have just pulled again from your latest master and it works great with all view sizes.
Thank you!
