### ISSUE TITLE
Updating Agent Color Based on Action

### ISSUE THREAD

**Issue by KenR22** [maximecb/gym-minigrid#143]
I am trying to override an action to change the color of the agent. I created a variable named agent_state. If the agent_state is less than 0 the agent will have one color, otherwise another. I have managed to update agent_state with an action and change color seperately. But cannot integrate both together. Any pointer would be helpful.
Rendering is done as "rgb_array"

I am working on the mingrid.py file which is attached as txt.
Thanks!
[minigrid.txt](https://github.com/maximecb/gym-minigrid/files/6810643/minigrid.txt)

**Comment by maximecb** [comment]
I'm not sure what you mean when you say you haven't managed to integrate both together. I would suggest printing the value of agent_state and agent_color in the render_tile method. You're going to need to do some detective work.

Just a tip on using GitHub: the best way to share code to discuss things like this is if you create a fork of this repository, and then you can easily copy and paste links to specific lines of code.
