### ISSUE TITLE
Extend the colors

### ISSUE THREAD

**Issue by gongzhitaao** [maximecb/gym-minigrid#145]
I'm trying to have thousands of simple tasks within the environment.  The tasks will be reaching objects, say "key", of different colors.  However, currently we only support limited number of colors.

I'm hacking the env to support more colors

```py
COLORS.update({
    f'{r},{g},{b}': np.array([r, g, b])  #
    for r in range(256) for g in range(256) for b in range(256)
})

COLOR_TO_IDX.update({
    f'{r},{g},{b}': 6 + r * 256 * 256 + g * 256 + b  #
    for r in range(256) for g in range(256) for b in range(256)
})
```

Do you think it worthwhile to incorporate the changes into the library?

Thanks!

**Comment by maximecb** [comment]
Hi @gongzhitaao. Feel free to do that in your fork but unfortunately I couldn't merge something like this, because there are many publications using MiniGrid, and I don't want to risk changing their results.
