### ISSUE TITLE
When to add gen_obs() in Observability wrappers?

### ISSUE THREAD

**Issue by patras91** [maximecb/gym-minigrid#147]
Hi, 
I am currently trying to add my own wrapper to have the observation of a fixed size. However, in some of the existing wrappers, there is a gen_obs() method, and some of the wrappers don't have it.

What is the logic behind when to add a gen_obs() function?

Thanks,
Sunandita

**Comment by maximecb** [comment]
Hi, I don't see `gen_obs()` in any of the wrappers in:
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py

?

**Comment by patras91** [comment]
Thanks for your quick response! I found out that my collaborator had added the gen_obs() in some of the wrappers because wrappers were not being correctly applied when the env is reset(). gen_obs() is being called during reset().

Do you see any potential side-effects of adding gen_obs() to the wrappers?

This our definition of gen_obs():

    def gen_obs(self):
        return self.observation(self.env.gen_obs())

**Comment by maximecb** [comment]
Normally if you're defining an observation wrapper you would only need to define the `observation` method:
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py#L110

But hey, if it works?

**Comment by patras91** [comment]
OK, thanks!
