### ISSUE TITLE
binary rewards in readme, but not in the code

### ISSUE THREAD

**Issue by IraKorshunova** [maximecb/gym-minigrid#149]
Hello!

I'm wondering if there is any good reason for assigning rewards as: 1 - 0.9 * (self.step_count / self.max_steps)
([this line](https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L824))?

The readme says that the rewards are 0 or 1, so I think either readme or the code should be fixed to avoid confusion. 

To me, the binary rewards seem more reasonable as the discount factor in the return computations already takes care of  encouraging the agent to reach the goal faster. 

Also, assuming that the agent doesn't know for how many steps it was running, it will have a hard time predicting the reward (and consequently value) if the reward depends on step_count. Such reward makes the environment even more partially-observable.
I think it needlessly makes the problem harder.

Anyway, thank you for this beautiful environment!

**Comment by maximecb** [comment]
Hello, I think you're probably correct but we wanted to give an incentive in the environment's reward to reach the goal faster, no matter the discount factor.
