### ISSUE TITLE
How to get encoding of all the tiles in the env?

### ISSUE THREAD

**Issue by unclebob7** [maximecb/gym-minigrid#151]
![image](https://user-images.githubusercontent.com/29818505/130195420-4214e54a-d53c-4893-b643-6116888000c9.png)

Hi! As shown in the above image (size=5\*5), instead of only getting the encoding of the agent's observation space (7\*7\*3), how can I manage to get full observation, i.e. the encoding of all the tiles in the env (5\*5\*3) at each step?

Thanks~

**Comment by maximecb** [comment]
Hello there. There are two wrappers that can do what you want:

https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py#L221
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py#L221
