### ISSUE TITLE
RGBImgObsWrapper returns partial observable environment

### ISSUE THREAD

**Issue by souradip-chakraborty** [maximecb/gym-minigrid#162]
#!pip install gym-minigrid
from gym_minigrid.wrappers import *
env = gym.make('MiniGrid-GoToDoor-6x6-v0')
env = RGBImgObsWrapper(env) # Get pixel observations
obs = env.reset() # This now produces an RGB tensor only
a1 = env.render('rgb_array')
plt.imshow(a1)

However, it is returning a partial observable view only. Is it possible to get the whole observation ?

**Comment by maximecb** [comment]
The observation should be fully observable, but you should get the observation via obs['image']
