### ISSUE TITLE
Error with Goal in view using RGBImgPartialObsWrapper

### ISSUE THREAD

**Issue by dlevenstein** [maximecb/gym-minigrid#163]
I get the following error whenever there's a Goal in view, when using the RGBImgPartialObsWrapper

  File "/Users/dl2820/Code Libraries/gym-minigrid/gym_minigrid/wrappers.py", line 210, in observation
    rgb_img_partial = env.get_obs_render(

  File "/Users/dl2820/Code Libraries/gym-minigrid/gym_minigrid/minigrid.py", line 1290, in get_obs_render
    grid, vis_mask = Grid.decode(obs)

  File "/Users/dl2820/Code Libraries/gym-minigrid/gym_minigrid/minigrid.py", line 618, in decode
    v = WorldObj.decode(type_idx, color_idx, state)

  File "/Users/dl2820/Code Libraries/gym-minigrid/gym_minigrid/minigrid.py", line 145, in decode
    v = Goal(color)

TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by dlevenstein** [comment]
Fixed by changing lines 164-165

from: 
class Goal(WorldObj):
    def __init__(self,):
        super().__init__('goal', 'green')

to: 
class Goal(WorldObj):
    def __init__(self, color='green'):
        super().__init__('goal', color)


Similar will probably need to be done for Lava, Home, Food, Water.

**Comment by maximecb** [comment]
This might be related to modifications you've made because a color argument is not passed to `Goal` in the `decode` method here: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L142

Which happens on line 142, not 145.

I could see a color to the `Goal` class, but not `Lava`

**Comment by dlevenstein** [comment]
Oh, this must be an edit in the fork I branched off of. My bad. thanks for the great tool! :)

**Comment by maximecb** [comment]
No problem, have fun :)
