### ISSUE TITLE
Width and height cannot be less than 3

### ISSUE THREAD

**Issue by epignatelli** [maximecb/gym-minigrid#166]
Hey Maxime, I just noticed that `Grid` does not allow for observations of 1 cell.
https://github.com/maximecb/gym-minigrid/blob/6116191b15aec9e09e4b48edd16f144e31b412fa/gym_minigrid/minigrid.py#L338-L339 

Given that a 1-cell grid does not make much sense, `Grid` is also used for defining agent views. Any reason why that is not:
```python
        assert width >= 1
        assert height >= 1
```
?

**Comment by maximecb** [comment]
Fair enough, we could change that to 1. Feel free to open a PR.
