### ISSUE TITLE
Agent rotation based on FullyObsWrapper

### ISSUE THREAD

**Issue by MarcoMeter** [maximecb/gym-minigrid#167]
Hi!

I made a custom environment that is wrapped using the FullyObsWrapper. Now I'm working on setting up my custom observation one-hot encoding. I've got a question concerning the agent's rotation.

The FullyObsWrapper provides the agent's position inside obs["image"]. Given the agent's position by some obs["image"][i,j], I get this piece of information [10, 0, 1] . 10 refers to the object ID. Does 1 refer to the agent's rotation?

**Comment by maximecb** [comment]
Hi Marco. Yes it does: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py#L241

Though maybe that should be better explained in the comments.

**Comment by MarcoMeter** [comment]
Thank you for the clarification!
