### ISSUE TITLE
manual_control.py not responding

### ISSUE THREAD

**Issue by ibagur** [maximecb/gym-minigrid#169]
First at all, many thanks for providing this fantastic and lightweight platform. I am using it to support my current studies in RL and so far it is working very nice, even with no GPU. One thing only, for some reason manual control is not working. The environment appears in the pop-up windows, and apparently key-strokes are detected (arrows, etc.), as there is an output on the Terminal giving feedback on both the key pressed and reward. But on the graphical output, the agent does not seem to react or move, therefore the reward from all manual key inputs is 0, as it is not possible to manually 'solve' the task. Any hints? My environment is as follows:

- Virtual environment with Python 3.7.9, on a MacOS 15.2, 
- gym 0.21.0
- gym-minigrid 1.0.2

Thanks!

**Comment by maximecb** [comment]
Hi @ibagur. Can you state which command you used to run `manual_control.py`, which environment, etc?

**Comment by ibagur** [comment]
Hi @maximecb , many thanks for your quick reply. I basically followed as stated in the README.md:

`./manual_control.py --env MiniGrid-Empty-8x8-v0` (Mission: get to the green goal square)

As I said, the graphical pop-up window appears as when running it algorithmically, but does not seem to respond to the manual key inputs. Key strokes are detected though (but nothing moves):

`pressed right
step=1, reward=0.00
pressed right
step=2, reward=0.00
pressed right
step=3, reward=0.00
pressed right
step=4, reward=0.00`

Thanks.

**Comment by maximecb** [comment]
I'm able to reproduce the bug locally. Also on MacOS here. I have to assume that something has changed in matplotlib which is preventing the graphics from being redrawn at every step. Investigating.

**Comment by maximecb** [comment]
I just pushed a fix and uploaded a new minigrid package v1.0.3. Let me know if that works for you.

**Comment by ibagur** [comment]
It works flawlessly now, many thanks for the fix!
