### ISSUE TITLE
Fetch does not seem to produce the negative reward

### ISSUE THREAD

**Issue by manuel-delverme** [maximecb/gym-minigrid#170]
> This environment has multiple objects of assorted types and colors. The agent receives a textual string as part of its observation telling it which object to pick up. Picking up the wrong object produces a **negative reward**.

**Comment by maximecb** [comment]
Good catch. It produces a zero reward. There used to be negative rewards but I found that this often made it hard to converge, because the agent tends to learn that doing nothing is better than acting, gets trapped in passive a local maxima.
