### ISSUE TITLE
pip version differences

### ISSUE THREAD

**Issue by aklein1995** [maximecb/gym-minigrid#171]
Hello!

Is there any significance difference between the version is uploaded to pip in the different versions?
With significance I refer to different reward functions, observations spaces...?

I am testing the differences between an approach that was executed at version 1.0.1 and I do not know if the results might slightly change in 1.0.3 (current).

Thank you in advance!

**Comment by maximecb** [comment]
There shouldn't be any difference in reward function. Recent changes have just been small bugfixes.
