### ISSUE TITLE
Removing objects or moving goal

### ISSUE THREAD

**Issue by raymondchua** [maximecb/gym-minigrid#175]
Hi!
Is there a way I can remove objects? I would like to move the goal (ie. change the goal position) after some iterations of training.

**Comment by maximecb** [comment]
There's a method `place_agent` to do this. Would recommend using `grep` to search through the source code for usage:
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L959

**Comment by raymondchua** [comment]
I tried the env.grid function but it did not work.

**Comment by maximecb** [comment]
Take a look at how objects are placed in the code for the existing environments, and how these functions are defined: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/envs/empty.py
