### ISSUE TITLE
Out of bounds labeled as walls

### ISSUE THREAD

**Issue by wbridewell** [maximecb/gym-minigrid#184]
For the agent's observations, any cells out of the bounds of the grid are labeled as walls. Since these cells are out of bounds and should be blocked off by walls anyway, it would be helpful in some situations either to label them as "unseen" or to create a new label for "out of bounds." 

https://github.com/maximecb/gym-minigrid/blob/29f8a0973549a54282b7f95cdd691a07bf2d218a/gym_minigrid/minigrid.py#L431

**Comment by maximecb** [comment]
I made that choice because the agent can't walk on the areas that are out of bounds 🤷‍♀️
