### ISSUE TITLE
Option for full observability

### ISSUE THREAD

**Issue by robertmacyiii** [maximecb/gym-minigrid#23]
I think this would be useful for use cases where we want learning to converge to a deterministic policy (which is not optimal in some of the partially-observable settings).  It would be nice to have this as an option, simply using the full grid encoding doesn't work because it doesn't represent the agent.

**Comment by maximecb** [comment]
Yes, a full view of the grid including the agent.

**Comment by d3sm0** [comment]
A lazy way of doing it would be something like this?

```python
class FullyObsWrapper(gym.core.ObservationWrapper):
    """
    Fully observable gridworld
    """

    def __init__(self, env):
        super().__init__(env)
        self.__dict__.update(vars(env))
        self.observation_space = spaces.Box(
            low=0,
            high=255,
            shape=(self.env.grid_size * 32, self.env.grid_size * 32, 3),  # number of cells
            dtype="uint8"
        )

    def observation(self, obs):
        if self.env.grid_render is None:
            return np.zeros(shape=self.observation_space.shape)  # dark screen as init state?
        return self.env.grid_render.getArray()
```

But how do you encode the direction of the agent? Maybe a tiled vector over the last dimension, so you will get the total obs as 800x800x4?

**Comment by maximecb** [comment]
If you render the whole grid that way and get the pixel data, then the agent will be visually rendered in there already.

**Comment by MishaLaskin** [comment]
Had the same question about rendering the whole grid. Using `img = env.render('rgb_array')` was a nice hack.

**Comment by d3sm0** [comment]
@maximecb there is a little issue about attributes sharing. The env has more attribute than the gym env, thus wrapping requires the attributes update at least for testing purposes, i don't think you use them in the standard setting.

Shall I keep it like this and forget for now, or try to refactor a little bit and submit a PR?

**Comment by maximecb** [comment]
@d3sm0 can you clarify what the issue is? May be nice to get a PR :)

**Comment by d3sm0** [comment]
@maximecb sure. The issue is that when you wrap some env in a gym.Wrapper instance, you loose access to the attributes of the env. Thus it doesn't pass the test unless you don't share the missing attributes with `self.__dict__.update(vars(env))` and your tests breaks. 

I'm solving #13 and PR :)

**Comment by maximecb** [comment]
Sweet. Thanks @d3sm0 !

**Comment by maximecb** [comment]
Working solution contributed by @d3sm0 in #24
