### ISSUE TITLE
Write the instruction in `env.render()` window

### ISSUE THREAD

**Issue by lcswillems** [maximecb/gym-minigrid#30]
Do you think it is possible to write the text in `env.render()` window (at the bottom)?

It would be a really nice feature because everything will be displayed in the same window. Currently, doing a gif with the grid and the text the one below the other is very hard: https://github.com/lcswillems/pytorch-a2c-ppo/blob/a0a19f994517a7fe198066685688ad66f50efa53/README-images/enjoy-gotodoor.gif

I need to precisely move my terminal and the rendering window.

**Comment by maximecb** [comment]
Implemented the feature you requested :)

**Comment by lcswillems** [comment]
Great!!
