### ISSUE TITLE
Index error in str encoding

### ISSUE THREAD

**Issue by d3sm0** [maximecb/gym-minigrid#41]
It seems like that the dictionary is outdated. I'm fixing it by adding the proper keys and values from the `OBJ_TO_IDX` dictionary. 

https://github.com/maximecb/gym-minigrid/blob/a6678d060dfa3afa7f572e9528f99a3d1fc3b356/gym_minigrid/minigrid.py#L802

**Comment by maximecb** [comment]
We should also add a test for the env to string encoding, to make sure we know if it breaks.

**Comment by maximecb** [comment]
I just rewrote the __str__ function and added a test :+1:
