### ISSUE TITLE
Extending Support for Four Rooms 

### ISSUE THREAD

**Issue by idigitopia** [maximecb/gym-minigrid#43]
**Different number of rooms in a gridworld fashion (no of rooms: 1 ,2,3,4 . .. . )**
_Baseline - 2 room gridworld, 2X2, top row - red room, bottom row – green room. No doors._

-
  - Can generate gridworld env with number of rooms as input
  - Should also take color of the rooms as input (default, same and options for all different)
  - Should also take the size of the gridworld as an input (default size is smallest grid has some number of grids.
  - Options for Doors (random placement)

**Different number of independent Agents. (number as input 1,2,3,4)**
_Baseline: 1 Agent at top left in the red room_

-
  - Random start places or fixed start places.
  - One grid can contain more than one agents ? ( flag)
  - Representation pixel styles of the Agent  (Random or different color or patterns)
  - Agent Properties:

-
  -
    - Partial or full observability. (front 3 by 3 grid) or front(triangle rather than square)
    - Agent can move in four 2-D directions
    - Agent can interact with other objects

-
  -
      -
        - Blocked by the wall
        - Pick a ball
        - Drop a ball
        - Open door ( lock and door environment)

**Different number of balls. ( 1,2,3,4)**
_baseline: 1 ball at the top right in the red room_

-
    - Random start place or fixed start places.
    - One grid can contain more than one agents ? ( flag)
    - Representation pixel styles of the Agent  (Random or different color or patterns)
    - Ball Properties :

-
  -
      - Balls can be picked up and dropped down.
      - Ball explodes (May be) (Additional Ball behavior according to color)

**Goal Condition**
_Baseline: Move the ball to green room, and the robot should also be in green room._

-
    - Move red balls to red room.
    - Or Move all balls to specified room.
    - Agent may be asked to get back to initial position or to any of the rooms.

**Comment by idigitopia** [comment]
Thank you for such a prompt response. 

I am trying to create a simple environment with colored rooms and balls where the agent can take the above-mentioned actions. I am actually trying to get the baseline working as of now. 

I see that there is a figure "fourroomqa-env.png" that is close to what I am trying to achieve. But I can't seem to be able to find how to get that particular env running.

**Comment by maximecb** [comment]
I removed FourRoomQA because it wasn't used or maintained, but you can still find the code here if you want to use that as a starting point: https://github.com/maximecb/gym-minigrid/blob/4a8cace595876b9021b48a9bd8b635dd6fa65c80/gym_minigrid/envs/fourroomqa.py

**Comment by idigitopia** [comment]
Hi Maxim, 
Thank you so much for the code. I tweaked the file to my requirements (room objects and goal condition). I also used the fully observable wrapper as you mentioned. 
But I can't seem to get rid of the mask that is rendered for depicting cells visible to the agent.

**Comment by maximecb** [comment]
The fully observable wrapper produces a grid as an observation. The render method is for human viewing, that doesn't change with the fully observable right now.
