### ISSUE TITLE
Why not make a pip package?

### ISSUE THREAD

**Issue by lcswillems** [maximecb/gym-minigrid#45]
Hi Maxime,

MiniGrid is growing fast!

I was wondering: why you don't create a pip package for MiniGrid? It would be easier to install your package. And why you don't create releases of your code? This way, you can do changes that are not backward compatible without breaking people's code. You can also detail the changes you did.

Best,
Lucas

**Comment by maximecb** [comment]
The problem is that other dependencies can be a moving target, something can still break even with pip packages. Though I agree this might help alleviate the problem.

How much work is it to create a pip package?

**Comment by floringogianu** [comment]
Until there's a package, this seems to work just fine if you want a single command install that also works with virtualenv config files: `pip install git+git://github.com/maximecb/gym-minigrid.git#egg=gym-minigrid`

**Comment by lcswillems** [comment]
I have created a package for `torch-rl`. The process can seem complicated but it is in fact very simple.

1. Create an account on https://pypi.org/account/register/
2. Install some packages `pip3 install --upgrade setuptools wheel twine`
3. In the root of the package, execute `python3 setup.py sdist bdist_wheel` to build it.
4. In the root of the package, execute `twine upload dist/*`.

Your package should be live at https://pypi.org/project/gym-minigrid/ .

I think it is worth to create a PyPI package because more people will then use your package. Moreover, it is ease to version your package by changing the version in `setup.py`.

**Comment by lcswillems** [comment]
I have just released that I could create the package for you (by executing the commands in the previous post). Hence, I created it. The package is [here](https://pypi.org/project/gym-minigrid/).

If you create an account to PyPI, I will add you as the owner of the package on PyPI.

I think you will also have to add :-1: 
```
build/*
dist/*
```
to your `.gitignore`.

**Comment by maximecb** [comment]
Thanks @lcswillems, I registered account `maximecb` on pipy and added those items to the `.gitignore`.

**Comment by lcswillems** [comment]
I added you to both repositories!

**Comment by maximecb** [comment]
Awesome, thanks.
