### ISSUE TITLE
RGB observation

### ISSUE THREAD

**Issue by Nicolas99-9** [maximecb/gym-minigrid#48]
Is there a way to receive an RBG observation instead of a matrix of values [0,3...].
Is there an option when I create the agent?

**Comment by maximecb** [comment]
Hi, yes there is. You can call the `env.get_obs_render()` method to generate images: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L1215

Note that this will produce a partial observation still, not a fully observable render. If you want a fully observable render, you can call `env.render('rgb_array')`.

**Comment by MarcoMeter** [comment]
How do you actually use `env.get_obs_render()`?

I tried it like this, but got a keyword argument exception on 'mode':

```python
import gym_minigrid
import gym
import numpy as np
import matplotlib.pyplot as plt


env = gym.make("MiniGrid-FourRooms-v0")
obs = env.reset()
env.render()

agent_frame = env.get_obs_render(obs["image"], mode="rgb_array")

plt.imshow(agent_frame)
plt.show()
```

**Comment by JeniaJitsev** [comment]
Related to that - is there an easy built-in way to mask out those parts of the environment that the agent cannot see from the current position (e.g due to walls, etc)?

**Comment by maximecb** [comment]
Hi @JeniaJitsev, the masking should be enabled by default. You are correct that the agent gets a different perception for empty and invisible cells, but right now there is no special rendering for invisible cells in the RGB render.

**Comment by maximecb** [comment]
@MarcoMeter Thanks for the heads up. I just pushed a package version 0.0.5 to pip

**Comment by JeniaJitsev** [comment]
Hey @maximecb, thanks for quick response and package update. We can have a look whether there is a straighforward simple way to incorporate an option for rendering of empty vs invisible cells to be different in image observation, so it can be then enabled / disabled given corresponding demand.

**Comment by JeniaJitsev** [comment]
Sure, will do
