### ISSUE TITLE
Fix numpy 1.15.4 dependency

### ISSUE THREAD

**Issue by floringogianu** [maximecb/gym-minigrid#52]
Hi, what is required for fixing the `numpy 1.15.4` dependency? I have a situation where `gym-minigrid` downgrades the `numpy` version installed by `pytorch` via `conda`.

**Comment by maximecb** [comment]
It looks like it's been fixed, I just pushed a commit without the exact numpy version requirement. Let's see if it passes the automated tests.

**Comment by maximecb** [comment]
Looks like all is good.

**Comment by floringogianu** [comment]
Thanks for quickly looking into this!
