### ISSUE TITLE
Potential rendering bug

### ISSUE THREAD

**Issue by danfeiX** [maximecb/gym-minigrid#56]
First of all, thanks for the great work! 

When I was trying to render an rgb array with the environment `MiniGrid-KeyCorridorS3R1-v0`, the image came out totally scrambled. It seems to be either because of it's an non-square environment or there's some issue with the RoomGrid superclass. Could you look into this? Thanks!

**Comment by danfeiX** [comment]
In https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/rendering.py#L151, shouldn't this be (height, width, 3)? Reshaping manually seem to fix the issue

**Comment by maximecb** [comment]
That could well be.

**Comment by maximecb** [comment]
I just pushed a commit. Can you tell me if that fixes the problem?
