### ISSUE TITLE
Option for observations as RGB array

### ISSUE THREAD

**Issue by planetceres** [maximecb/gym-minigrid#6]
It would allow for a greater range of use cases if there was an option that could be passed to train using RGB arrays instead of only the image encodings. The readme [describes](https://github.com/maximecb/gym-minigrid#design) a way to do this with `get_obs_render`, but it would be nice if it could be included as an argument. 

Would you consider adding something like this?

https://github.com/planetceres/gym-minigrid/commit/9c2ae3c7a8614a69f6f22e5c86ac2c6731b03af2

**Comment by maximecb** [comment]
I think that the cleanest way to do this would be to create a separate wrapper that just produces an RGB image, and maybe also drops the text string if you don't need it. I would create a separate wrapper rather than setting some boolean variable on the environment. If you create that, I would merge it.

**Comment by planetceres** [comment]
Optionally dropping the text string for baseline comparisons was another priority for me, so I'm glad you mentioned that. I had started with the wrapper approach and agree it makes more sense, but I was trying to avoid creating multiple wrappers for each variant of image type along with optional text. This may not be a concern though if the observation wrappers are more meant as a temporary solution to deal with dict observations.

**Comment by planetceres** [comment]
This makes sense to me based on the current wrapper syntax, although could use some refactoring later at some point:

https://github.com/planetceres/gym-minigrid/commit/b16c3f68a42bc973fd3851d13d3f2f1d7089b16f

**Comment by maximecb** [comment]
I don't think the wrappers are just a temporary solution. I think different people will want different inputs for their use cases. I think it's just cleaner to separate the environment from wrappers that format the output however you want it.

I would just create an RGBImageWrapper, which doesn't flatten the image and doesn't include the text (no boolean argument).
