### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by RasmusRavnFrost** [maximecb/gym-minigrid#63]
I found a bug in the Dynamic Obstacles environemnt. When I run the script below I get an assertion error after not so many iterations.

    import random
    import time
    import gym
    from gym_minigrid import *

    env = gym.make("MiniGrid-Dynamic-Obstacles-5x5-v0")
    while True:
        action = random.randint(0, 6)
        observation, reward, done, info = env.step(action)
        # env.render("human")
        # time.sleep(1/20)
        if done:
            env.reset()

**Comment by maximecb** [comment]
Can you paste the assertion that you get?

**Comment by RasmusRavnFrost** [comment]
Traceback (most recent call last):
  File "C:\Users\Frost\Documents\Dropbox\ITU\KurserITU\Thesis Project\Repository\src\tests\minigrid-obstacles-bug-example.py", line 11, in <module>
    observation, reward, done, info = env.step(action)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\gym_minigrid\envs\dynamicobstacles.py", line 75, in step
    self.grid.set(*old_pos, None)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\gym_minigrid\minigrid.py", line 401, in set
    assert i >= 0 and i < self.width
AssertionError

**Comment by RasmusRavnFrost** [comment]
I have been trying to figure out whats happening and somehow 
one of the obstacles cur_pos has assummed the  value [-1, -1] but I don't know why

**Comment by RasmusRavnFrost** [comment]
I found the problem:
The agent successfully picked up one of the obstacles (which sets the obstacles current position to [-1, -1])
Then when the obstacle tried to move it realizes that its current position is out of the grid and raises an error.

The obvious fix is to stop allowing the obstacles to be picked up by adding this in 
dynamicobstacles.py : DynamicObstaclesEnv._gen_grid()
`
        ...
        # Place obstacles
        if self.show_obstacles:
            self.obstacles = []
            for i_obst in range(self.n_obstacles):
                self.obstacles.append(Ball())
                self.obstacles[-1].can_pickup = lambda: False
                self.place_obj(self.obstacles[i_obst], max_tries=100)
`

**Comment by maximecb** [comment]
Technically, the bug is on your end, because you're not respecting the action space of the environment, see `env.action_space.n`.

But, I added a check for invalid actions to prevent more people running into this.
