### ISSUE TITLE
RecursionError in DynamicObstacles-Random-6x6

### ISSUE THREAD

**Issue by floringogianu** [maximecb/gym-minigrid#68]
I got this in the middle of training on `DynamicObstacles-Random-6x6`. Not sure exactly how to reproduce it, I will try to run more experiments and see how often it happens.

```sh
  File "/opt/conda/envs/torch110/lib/python3.7/site-packages/gym/core.py", line 273, in step
    observation, reward, done, info = self.env.step(action)
  File "/opt/conda/envs/torch110/lib/python3.7/site-packages/gym_minigrid/envs/dynamicobstacles.py", line 75, in step
    self.place_obj(self.obstacles[i_obst], top=top, size=(3,3), max_tries=100)
  File "/opt/conda/envs/torch110/lib/python3.7/site-packages/gym_minigrid/minigrid.py", line 923, in place_obj
    raise RecursionError('rejection sampling failed in place_obj')
RecursionError: rejection sampling failed in place_obj
```

**Comment by maximecb** [comment]
Thanks @floringogianu. That error happens when `place_obj` tries to move an object and can't find a spot. A potential fix might be to add a try statement around `place_obj`, and simply not move the object if a new position for it can't be found.

**Comment by maximecb** [comment]
I pushed some changes to the dynamic obstacles environment that I believe address this issue and make the environment a bit more logical (you only lose if you walk into something you can actually see is in front of you, rather than if anything ever jumps in front of you). Let me know if you run into any other problems :)

**Comment by floringogianu** [comment]
@maximecb Thanks for looking into this and I apologize for not following up and just posting the error - I was in a middle of a deadline.
