### ISSUE TITLE
1x1 Room sizes

### ISSUE THREAD

**Issue by manuel-delverme** [maximecb/gym-minigrid#70]
https://github.com/maximecb/gym-minigrid/blob/999599a412db112bc7efa9a0f72f8c315074f8bb/gym_minigrid/envs/multiroom.py#L201

Can this be turned into:
```topX + self._rand_int(1, sizeX) - 1```

To allow for rooms to be 1x1 size?

**Comment by maximecb** [comment]
The size of the rooms includes walls. You probably want a 3x3 room?

**Comment by manuel-delverme** [comment]
Silly mistake :)
Thanks for the prompt answer
