### ISSUE TITLE
How can I transform the render ?

### ISSUE THREAD

**Issue by DamienAllonsius** [maximecb/gym-minigrid#71]
Hello, 
I'm using gym-minigrid and I need to get the rendering image, transform it and then display it.

After the "transformation", I get a np.array matrix with 3 channels (RGB). Is there a way to give this result to the environment (for instance the Render class ?) in order to display it ?

Thanks in advance !

PS: In other environment, I used to do something like
```
from gym.envs.classic_control import rendering

env_unwrapped = gym.make("...").env.unwrapped

img = env_unwrapped.ale.getScreenRGB2()
image_transformed = .... 

if env_unwrapped.viewer is None:
    env_unwrapped.viewer = rendering.SimpleImageViewer()

env_unwrapped.viewer.imshow(image_transformed)
return env_unwrapped.viewer.isopen
```
but apparently `env_unwrapped` has no attribute `viewer`.

**Comment by maximecb** [comment]
Hi @DamienAllonsius. I'm not quite clear on what you want to do. I'm assuming you want to transform the observations the agent gets by processing them as RGB images?

One thing you should be aware of is that the image that you see when running `manual_control.py`, that is the human-viewable input, is not the same as what the agent sees. The agent gets a partially observable view of the environment that is encoded as a (7,7,3) array, which is *not an image*, but rather an encoding of the grid cells in front of the agent. What you see in `manual_control.py` is a rendering of the whole grid as an RGB image, which is produced by a call to `env.render('human')`.

The easiest way to transform what the agent sees is using a wrapper, see the code in [`wrappers.py`](https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py#L115) for some examples. There is a wrapper that transforms the input the agent gets into an RGB image, which may be a good starting point for what you want to do.

**Comment by DamienAllonsius** [comment]
Hi @maximecb Thanks a lot for your answer !
No, I really want to transform the rendering, not the observation.
I already give this observation to my agent
```
env.render(mode='rgb_array', highlight=False)
```
But then I transform the matrix by applying some downsampling with `cv2`, and I would like to see the render. Is that possible ? Thanks a lot Maxime 
(sinon je suis français, on peut aussi communiquer par mail dans notre langue si tu préfères)
Damien

**Comment by maximecb** [comment]
You would have to modify the renderer class or create your own window using PyQT or Pyglet. The slightly annoying part is that you have to convert the rgba array into a QPixmap object, basically. Then the `Window` class here has a `setPixmap` method that you can use: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/rendering.py#L55

It's a bit annoying but definitely doable: https://stackoverflow.com/questions/34232632/convert-python-opencv-image-numpy-array-to-pyqt-qpixmap-image

If you do it, maybe you could add a method to the `Window` class to set what is being displayed from a numpy rgba array and create a pull request? :)

**Comment by DamienAllonsius** [comment]
Thanks for your answer. Ok I'm on it.

**Comment by DamienAllonsius** [comment]
Following the [stackoverflow advices]( https://stackoverflow.com/questions/34232632/convert-python-opencv-image-numpy-array-to-pyqt-qpixmap-image), I made a new function in `Renderer` class
```
    def drawArray(self, rgb_array):
        from PyQt5.QtGui import QPixmap

        height, width, _ = rgb_array.shape
        bytes_per_line = 3 * width

        qt_img = QImage(rgb_array, width, height, bytes_per_line, QImage.Format_RGB888)  # .rgbSwapped()
        pixmap = QPixmap(qt_img)

        if self.window.closed:
            self.window = None
        else:
            self.window.setPixmap(pixmap)
            self.app.processEvents()
```
But I get a `segmentation fault` when I run it. Any Idea ?

**Comment by maximecb** [comment]
I don't think that you can just pass the numpy array directly. You will need to get a pointer to the data it contains using `ctypes`. Something like:

```
import ctypes

rgb_array = np.ascontiguousarray(rgb_array)
ptr = rgb_array.ctypes.data_as(ctypes.POINTER(ctypes.c_char))
qt_img = QImage(ptr, ...)
```

The ascontiguousarray call is to make sure the memory is all in one contiguous block.

References:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ctypes.html
https://docs.python.org/3/library/ctypes.html
