### ISSUE TITLE
Get position of the goal

### ISSUE THREAD

**Issue by wassimseif** [maximecb/gym-minigrid#73]
Is there a way to get the position ( x, y) of the goal?

I could get which grid is my goal by this loop 

```python
    for grid in env.grid.grid:
        if grid is not None and grid.type == "goal":
            print("This grid is my goal")
```
but I don't know how to map this to an (x,y) coordinates

**Comment by maximecb** [comment]
Hi @wassimseif, you should be able to do `grid.cur_pos` to get the x, y position. This is a numpy array of two values.

**Comment by maximecb** [comment]
That is a bug. I just pushed some code which should address it. Let me know if you run into other problems :)
