### ISSUE TITLE
Can I change the origin of observation?

### ISSUE THREAD

**Issue by mzwang828** [maximecb/gym-minigrid#74]
Hello,
Is there a way to change the origin of observation? Currently the observation covers the 7*7 area "in the front" of the agent. I'm wondering if I can change it so that the observation will be a 7*7 area centered at the agent's position.

**Comment by maximecb** [comment]
There's no built-in provision to do it, but it wouldn't be too hard to modify the code to make it happen.

This piece of code determines the extents of the box the agent can see. The code would actually become simpler if it were centered around the agent: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L1044

You'll want to either disable or modify the visibility checking algorithm. There's a piece of code to make it so the agent can't see through walls:
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L601

This can also be disabled by setting `see_through_walls=True`: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L673

**Comment by mzwang828** [comment]
Thank you! I think I got it. 
I made 2 changes in the minigrid.py file.
I changed the get_view_exts() method as you suggested so that the observation box is centered at the agent.
I didn't change the process_vis() method. Instead, I change agent_pos parameter passed to process_vis() so that the mask is also generated with the agent as center: https://github.com/maximecb/gym-minigrid/blob/081982e0652f25f814bdb5e6ecdeb6a8b08e45d0/gym_minigrid/minigrid.py#L1193

I think these 2 changes are enough to achieve the agent centered observation. Do you think if there's anything I'm missing? Thanks again!

**Comment by maximecb** [comment]
I think that process_vis might not quite work right with the agent position at the center, because it propagates visibility forward in the direction the agent is facing, so it won't handle what's behind.

**Comment by mzwang828** [comment]
I see. You are right about this. I will just set it to see through the walls for now.
