### ISSUE TITLE
NumPy-based renderer (eliminate PyQT dependency)

### ISSUE THREAD

**Issue by maximecb** [maximecb/gym-minigrid#76]
Some users have difficulties installing PyQT, on clusters in particular. It would be useful to build a renderer which uses NumPy instead of PyQT. This should not be too complicated to do given that the 2D graphics of MiniGrid are very simple.

The first step will be to evaluate what the performance impact might be. A caching strategy may need to be used to maximize performance.

**Comment by maximecb** [comment]
@mcmachado will you be available to help me test this?

**Comment by maximecb** [comment]
Hi @mcmachado. I have the new version of MiniGrid that uses NumPy to produce graphics on a new branch `maximecb-numpy-render`, and matplotlib for rendering windows. Could you test it out and let me know if you run into any issues?

**Comment by maximecb** [comment]
This is now pushed to the master branch :)

**Comment by abrsvn** [comment]
Hi,

Is it possible that this issue I just opened here:

https://github.com/lcswillems/rl-starter-files/issues/36

is in fact related to the recent push to master?

Thanks!

**Comment by maximecb** [comment]
Yes it is related. The new version of MiniGrid uses matplotlib for the rendering window instead of PyQT. Looking into how to make this work again.

**Comment by maximecb** [comment]
I made a pull request on the RL repository to update it following the minigrid changes.

**Comment by abrsvn** [comment]
thanks a lot!

**Comment by maximecb** [comment]
Feature is complete and seems to be working well. If anyone encounters bugs related to this, please open a new issue.
