### ISSUE TITLE
Wrappers not working correctly

### ISSUE THREAD

**Issue by mjanschek** [maximecb/gym-minigrid#78]
Hello,

RGBImgObsWrapper() seems to not extract the dictionary items anymore.

EDIT: Really great env nonetheless :-)

**Comment by mjanschek** [comment]
Tested with 1.0.0 and 0.0.6
It works correctly with 0.0.5

Is this correct or am i just confusing the purpose of this wrapper? I understand it delivers frames only like gyms arcade envs.

**Comment by maximecb** [comment]
Did you try what's suggested in the readme:

```
from gym_minigrid.wrappers import *
env = gym.make('MiniGrid-Empty-8x8-v0')
env = RGBImgPartialObsWrapper(env) # Get pixel observations
env = ImgObsWrapper(env) # Get rid of the 'mission' field
```

**Comment by maximecb** [comment]
Closing for now, but feel free to comment if you run into any more issues.
