### ISSUE TITLE
Installation instructions did not work.

### ISSUE THREAD

**Issue by elpidiovaldez** [maximecb/gym-minigrid#80]
I followed the installation instructions but I did not get a working minigrid system.

I installed in a conda virtual environment.  First I did: 

```
source activate tf
pip3 install gym-minigrid
./manual_control.py

```
But there is no manual_control file created in the current directory or anywhere else that I could find.

Then I tried the other installation method:

```
git clone https://github.com/maximecb/gym-minigrid.git
cd gym-minigrid
pip3 install -e .

```

After this I saw a copy of manual_control.py which succeeded in a running a simple environment.  However I could not load other environments. The following (taken from the instructions) failed:
`./manual_control.py --env_name MiniGrid-Empty-8x8-v0
`
I believe the problem is conda not knowing the correct path for the packages, but it is my experience that 95% of any problem using python is getting it to use the right installer, package versions, paths and interpreter.

**Comment by elpidiovaldez** [comment]
I found the problem.  The invocation line given in the instructions is wrong. It should be:

`./manual_control.py --env MiniGrid-Empty-8x8-v0`

ie --env instead of --env_name

**Comment by maximecb** [comment]
Hi, yes you're right, I forgot to update the instructions in the README. Will do that now.
