### ISSUE TITLE
Add optional goal compass

### ISSUE THREAD

**Issue by minuteman1911** [maximecb/gym-minigrid#84]
An optional observation variable that points to the direction of the first goal rather than the orientation of the agent. The observable image in itself provides very little information for the agent to advance ( even if a human looked at the partially observable grid, they would have to rely on mere random guessing ). This need for the agent to take arbitrary steps to discover the grid further could be removed.
The direction can be simply the tan inverse of the difference of goal and current position:
dir_radians = numpy.arctan( (goal[1] - agent_pos[1]) / (goal[0]  - agent_pos[0]) )

**Comment by maximecb** [comment]
Hi @minuteman1911 

I think the cleanest way to do this might be to create an [ObservationWrapper](https://www.programcreek.com/python/example/98676/gym.ObservationWrapper) that adds this information to the `info` object.

There are already a few wrappers implemented in [wrappers.py](https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/wrappers.py). If you'd like to implement this, I will accept a pull request.

**Comment by minuteman1911** [comment]
Hi,
Thank you for your response! I'll submit a pull request.
