### ISSUE TITLE
Why there is an extra dimension in flatten observation?

### ISSUE THREAD

**Issue by pengzhenghao** [maximecb/gym-minigrid#86]
Hi there! Thanks for you guys create this really interesting environments!

I am wondering why the observation_space of an observation-flatten environment contain an extra first dimension. The obs space is `Box(1, xxx)` while the observation itself is a vector with shape `(xxx, )`

Doing this violates the rules of gym space, and may cause error in some application.

```
env = gym_minigrid.wrappers.FlatObsWrapper(gym.make("MiniGrid-Empty-8x8-v0"))

env.observation_space
Out[20]: Box(1, 2739)

env.reset().shape
Out[21]: (2739,)
```

In some application the observation is checked via:

```
obs = env.reset()

env.observation_space.contains(obs)
Out[23]: False
```

and thus this will cause problem.

**Comment by maximecb** [comment]
Hi @pengzhenghao. I just pushed the change removing the extra dimension. Thanks for pointing this out.
