### ISSUE TITLE
Probably a bug in RGBImgPartialObsWrapper

### ISSUE THREAD

**Issue by tudor-berariu** [maximecb/gym-minigrid#91]
When using `RGBImgPartialObsWrapper` I get an error:
```
 File ".../lib/python3.7/site-packages/gym_minigrid/wrappers.py", line 200, in __init__
    obs_shape = env.observation_space['image'].shape
TypeError: 'Dict' object is not subscriptable
```

I think it should be
`obs_shape = env.observation_space.spaces['image'].shape`
instead of
`obs_shape = env.observation_space['image'].shape`

https://github.com/maximecb/gym-minigrid/blob/1e8b22e92b02a23fb4f85e0509815a41693aee75/gym_minigrid/wrappers.py#L200

**Comment by maximecb** [comment]
It seems that both ways work, but I will change it just to make it consistent.
