### ISSUE TITLE
Saving and restoring states

### ISSUE THREAD

**Issue by hasanferit** [maximecb/gym-minigrid#95]
Does this environment support saving and restoring states?

For example, I want to save an exact map state in **MiniGrid-Dynamic-Obstacles-5x5-v0** at some point and later I should be able to make the agent start from the saved state.

Gym's Atari environment has such a functionality: https://github.com/openai/gym/issues/402#issuecomment-260733260

**Comment by maximecb** [comment]
Provided that you haven't opened a window to do human rendering, you should be able to pickle and unpickle environments directly with Python's pickle module.

Let me know if that doesn't work correctly.
