### ISSUE TITLE
Bug: agent's view rectangle calculation

### ISSUE THREAD

**Issue by pkuderov** [maximecb/gym-minigrid#96]
Environment: `MiniGrid-Empty-5x5-v0`  
Wrappers: `ImgObsWrapper` + `ViewSizeWrapper`

When the `agent_view_size` is even (e.g. 6 as in the example below), an agent observes:

```
######
######
######
X--###
---###
--^-##
```

instead of

```
######
######
######
X--###
---###
--^###
```

Legend: `#` walls, `-` empty, `X` goal, `^` agent facing up (forward).

As you see, there's an empty cell on the right of an agent, while in reality (in environment's grid) there's a wall.

This particular behavior is the effect of [this line of code](https://github.com/maximecb/gym-minigrid/blob/1a29011da452069d77858afb2a2c96f0c8aee2a2/gym_minigrid/minigrid.py#L1191), which "places" an agent himself here (or what he carries). Actually, there's no bug here.

But the real cause is in how agent's view rectangle is calculated in [get_view_exts](https://github.com/maximecb/gym-minigrid/blob/1a29011da452069d77858afb2a2c96f0c8aee2a2/gym_minigrid/minigrid.py#L1031). There, `topX` and `topY` calculation doesn't take into consideration that in case of even `agent_view_size` the number of cells on the left and on the right of an agent is different.

E.g. in case of `agent_view_size = 6`, an agent views 3 cells on the left and 2 on the right (plus 1 he is at, which sums in 6): `---^--`. And for `agent_view_size=7`, an agent views 3 cells both on the left and on the right: `---^---`

**Comment by maximecb** [comment]
I'd be inclined to add an assert to disallow even view sizes. Do you have a use case in mind where that's genuinely useful?

**Comment by pkuderov** [comment]
Well, that's a good idea too. Why I didn't think of it in first place making bug fix PR? :( I just haven't seen any mentions that _it was supposed to be odd_ and thought/acted accordingly.
 
For me it's useful to have more granularity at choosing view size during initial hack-n-debug with an agent - when you play with simple small size environments and hence small view sizes, because such granularity makes sense only in a case of small sizes. I'd even thought of an option to set rectangular view area.

Of course, it's not mandatory and not critical at all. And, even more, you can crop observation manually with a custom observation wrapper - which will do the work except for the rendering (which is fine).

**Comment by maximecb** [comment]
I've added assertions to check that the view size is odd and >= 3. Sorry for rejecting the PR.
